name: dockerhub

on:
  push

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3.0.0

    - name: Set up Docker Buildex
      uses: docker/setup-buildx-action@v3.2.0

    - name: Login to DockerHub
      uses: docker/login-action@v3.1.0
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}

    - name: Build & Push
      id: docker_build
      uses: docker/build-push-action@v5.3.0
      with:
        push: true
        tags: torbovski/github-actions:latest

    - name: Image digest
      run: echo ${{steps.docker_build.outputs.digest}}
        
