# This workflow executes several linters on changed files based on languages used in your code base whenever
# you push a code or open a pull request.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/github/super-linter
name: Lint Code Base and Build & Push to DockerHub

on: 
  push
jobs:
  super-lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "master"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  docker:
    name: Build & Push to DockerHub
    needs: [super-lint]
    runs-on: ubuntu-latest

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3.0.0

    - name: Set up Docker Buildex
      uses: docker/setup-buildx-action@v3.2.0

    - name: Login to DockerHub
      uses: docker/login-action@v3.1.0
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}

    - name: Build & Push
      id: docker_build
      uses: docker/build-push-action@v5.3.0
      with:
        no-cache: true
        push: true
        tags: reeturn01/github-actions:latest

    - name: Image digest
      run: echo ${{steps.docker_build.outputs.digest}}
        
